In [1]:
!pip install transformers
!pip install "transformers[torch]"

Requirement already satisfied: transformers in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (5.8.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (1.14.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: numpy>=1.17 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2.2.6)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: packaging>=20.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (26.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2026.4.4)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: colorama in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: click>=8.2.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers) (8.3.3)
Requirement already satisfied: anyio in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: certifi in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: h11>=0.16 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: transformers[torch] in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (5.8.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (0.7.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (1.14.0)
Requirement already satisfied: numpy>=1.17 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (2.2.6)
Requirement already satisfied: pyyaml>=5.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (4.67.3)
Requirement already satisfied: packaging>=20.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (26.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (0.25.1)
Requirement already satisfied: torch>=2.4 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (2.11.0)
Requirement already satisfied: accelerate>=1.1.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from transformers[torch]) (1.13.0)
Requirement already satisfied: psutil in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.2.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.29.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.4.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: jinja2 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: setuptools<82 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from torch>=2.4->transformers[torch]) (65.5.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from torch>=2.4->transformers[torch]) (3.4.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: colorama in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.27->transformers[torch]) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers[torch]) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers[torch]) (0.0.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from typer->transformers[torch]) (15.0.0)
Requirement already satisfied: certifi in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.13)
Requirement already satisfied: anyio in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.13.0)
Requirement already satisfied: h11>=0.16 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (4.1.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from rich>=13.8.0->typer->transformers[torch]) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers[torch]) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\dexter\appdata\local\programs\python\python310\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.1)

[notice] A new release of pip is available: 23.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
from transformers import (
    T5Tokenizer,
    Trainer,
    TrainingArguments,
    T5ForConditionalGeneration
)

In [3]:
train_data=pd.read_csv(f"data/samsum-train.csv")
vals_data=pd.read_csv(f"data/samsum-validation.csv")

In [4]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [5]:
train_data.shape

(14732, 3)

In [7]:
train_data['dialogue'][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [10]:
vals_data.shape

(818, 3)

In [8]:
train_data.sample(10)

,id,dialogue,summary
1029,13818713,Paige: How do you like my new kettle? :D\r\nPa...,Paige sends a picture of her new kettle.
13542,13729934,Diamond: Is it raining?\r\nJulio: How the f do...,Julio doesn't know if it's raining.
748,13681893,"Ned: Hi, where are you?\r\nNina: Hi. M5\r\nNed...","Nina is at M5, she is having a lunch break, th..."
8458,13682618,Carol: a very big thank you for yesterday even...,Carol is going to have a 3-hours long individu...
7004,13681220,Lucy: omg did you see JK this morning?\r\nSue:...,Sue doesn't watch JK any more as it's disgusting.
9863,13864547,Terry: So it happened! I didn't expect the par...,Nationalists are protesting against parliament...
4903,13809963,Liam: John called\r\nLiam: asked if we have pl...,John will come to New Year's Eve party and bri...
11757,13680898,Isaac: it's white outside <3\r\nIvy: maybe whe...,It's white outside Isaac's window. According t...
623,13728214,Dave: It's curious how of all religions ever c...,Dave wonders why Christianity appeared to be t...
5433,13864386,Camille: A friend is looking for a job \nCamil...,Camille's friend from Romania just arrived in ...

### Ramdom Sampleing

In [11]:
train_data=train_data.sample(n=4000,random_state=42).reset_index(drop=True)
val_data=vals_data.sample(n=500,random_state=42).reset_index(drop=True)

In [ ]:
trainda